### ISSUE TITLE
Error: (converted from warning) `progress_estimated()` was deprecated in dplyr 1.0.0.

### ISSUE THREAD

**Issue by scottpeckham** [Huh/collar#82] opened 2023-03-18 17:29 UTC
I'm getting this error when pulling mortality statuses from code that previously executed (presumably with a warning). Any help would be appreciated. It appears that there is now a 'progress' package that handles such things instead of dplyr.

Downloading Vectronics collar data...
Error: (converted from warning) `progress_estimated()` was deprecated in dplyr 1.0.0.
ℹ The deprecated feature was likely used in the collar package.
Please report the issue at <https://github.com/Huh/collar/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.

**Comment by Huh** [comment] 2023-03-20 19:24
Thanks for pointing this out @scottpeckham. I will track this down within a day or so and report back.

**Comment by Huh** [comment] 2023-03-20 22:33
@scottpeckham I could not reproduce this error using the examples from the help text. Can you tell me which version of dplyr you are using or provide a way that I can reproduce the error? Do you get the error when running the examples under `?fetch_vectronics`? Perhaps I need a longer running operation to see the error.

In the interim, I will dig through the code to look for other deprecated functions.

My sessionInfo:

```r
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.2.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] collar_0.0.4004 testthat_3.1.4  devtools_2.4.4  usethis_2.1.6  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9        prettyunits_1.1.1 ps_1.7.1          assertthat_0.2.1  rprojroot_2.0.3  
 [6] digest_0.6.31     utf8_1.2.2        mime_0.12         R6_2.5.1          evaluate_0.15    
[11] highr_0.9         httr_1.4.4        ggplot2_3.4.0     pillar_1.8.0      rlang_1.0.6      
[16] curl_5.0.0        rstudioapi_0.14   miniUI_0.1.1.1    callr_3.7.1       urlchecker_1.0.1 
[21] stringr_1.4.0     htmlwidgets_1.5.4 RCurl_1.98-1.8    munsell_0.5.0     shiny_1.7.2      
[26] compiler_4.2.1    httpuv_1.6.5      xfun_0.31         pkgconfig_2.0.3   pkgbuild_1.3.1   
[31] htmltools_0.5.3   tidyselect_1.2.0  tibble_3.1.8      fansi_1.0.3       crayon_1.5.1     
[36] dplyr_1.0.9       withr_2.5.0       later_1.3.0       bitops_1.0-7      brio_1.1.3       
[41] grid_4.2.1        jsonlite_1.8.4    xtable_1.8-4      gtable_0.3.1      lifecycle_1.0.3  
[46] DBI_1.1.3         magrittr_2.0.3    scales_1.2.1      cli_3.6.0         stringi_1.7.8    
[51] cachem_1.0.6      fs_1.5.2          promises_1.2.0.1  remotes_2.4.2     xml2_1.3.3       
[56] ellipsis_0.3.2    generics_0.1.3    vctrs_0.5.1       tools_4.2.1       glue_1.6.2       
[61] purrr_0.3.4       processx_3.7.0    pkgload_1.3.0     fastmap_1.1.0     colorspace_2.0-3 
[66] sessioninfo_1.2.2 memoise_2.0.1     knitr_1.39        profvis_0.3.7    
```

**Comment by Huh** [comment] 2023-03-20 23:01
@scottpeckham I found the deprecated function call and updated it to use the progress package.

Could you please install from the develop branch and confirm that the change solves your issue?

```R
install_github("Huh/collar", ref = "develop")
```

Thanks,

Josh

**Comment by Huh** [comment] 2023-03-20 23:09
Thanks for the session info @scottpeckham. I see you are a version of dplyr ahead of me and that may be the explanation of the difference. The CRAN NEWS page for the package suggests that yes, as of 1.1.0, the use of progress is deprecated. IF this solution works for you then I think we found the issue and addresses it appropriately.

[dplyr 1.1.0 NEWS](https://cran.r-project.org/web/packages/dplyr/news/news.html)

Thanks for bringing this to my attention!

**Comment by scottpeckham** [comment] 2023-03-20 23:13
I installed the development branch and can confirm that did indeed successfully remove the error when running both the  example in ? fetch_vectronics and a longer running test on large batch of key files.

Thank you!

**Comment by Huh** [comment] 2023-03-20 23:27
Awesome, thanks for doing that so quickly. I will close this issue, but if anything else comes up please don't hesitate to reach out.

**Closed by Huh** 2023-03-20 23:27 UTC
